/*
 * generated by Xtext
 */
package org.arccore.gdbsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class GdbslUiModule extends org.arccore.gdbsl.ui.AbstractGdbslUiModule {
	public GdbslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
