/*
 * generated by Xtext
 */
package org.arccore.gdbsl.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.arccore.gdbsl.ui.internal.GdbslActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class GdbslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return GdbslActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return GdbslActivator.getInstance().getInjector(GdbslActivator.ORG_ARCCORE_GDBSL_GDBSL);
	}
	
}
