/*
* generated by Xtext
*/
package org.arccore.gdbsl;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class GdbslUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.arccore.gdbsl.ui.internal.GdbslActivator.getInstance().getInjector("org.arccore.gdbsl.Gdbsl");
	}
	
}
