/*
 * generated by Xtext
 */
package org.arccore.gdbsl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class GdbslRuntimeModule extends org.arccore.gdbsl.AbstractGdbslRuntimeModule {

}
