/*
* generated by Xtext
*/
package org.arccore.gdbsl.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class GdbslAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("org/arccore/gdbsl/parser/antlr/internal/InternalGdbsl.tokens");
	}
}
