/*
* generated by Xtext
*/
package org.arccore.gdbsl.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.arccore.gdbsl.services.GdbslGrammarAccess;

public class GdbslParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private GdbslGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.arccore.gdbsl.parser.antlr.internal.InternalGdbslParser createParser(XtextTokenStream stream) {
		return new org.arccore.gdbsl.parser.antlr.internal.InternalGdbslParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}
	
	public GdbslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(GdbslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
